### ISSUE TITLE
Relate Council to District during  indexing

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#14]
Relate both DEs as they are in the Contact Log stage

![image](https://user-images.githubusercontent.com/44774809/92284362-0cda0380-eebf-11ea-8c33-b0a8b0889344.png)

**Comment by chauthutran** [comment]
I have a hard time to understand it. Could you explain more details here with scenario, let me know what different between the old screen and this new screen, ... ?

**Comment by nancyespinoza** [comment]
Hi Tran! Yes, the idea is when the user select a District, only show the councils correspondent to that district. I think the logic is based on the codes. For example, if the user selects 01. Maseru, then the councils available should be the ones that start with 01 (Maseru Central - MCC (013201), Qiloane A01 (013701), etc.)
![20200904170236](https://user-images.githubusercontent.com/44774809/92290284-d9a07000-eed0-11ea-92bc-73d985a9b44b.gif)

**Comment by chauthutran** [comment]
I see. I think I got it. Thank you.
