### ISSUE TITLE
Logic for 'To Come Back (months/12)' DE

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#15]
Show DE LS HTS TRK - Comments/TCB - To Come Back (months/12) (BZxUgzX4BpO) only if LS HTS TRK - Test - Final HIV status (UuKat0HFjWS) is 'Negative'

**Comment by chauthutran** [comment]
HI Nancy,

Where should  I show this data element ? In "Add Relationship Form" ?? 
And where should I put this data value ? Should it be in Contact Log Event ??
Should we add more this data element in Contact Log event form in Add/Update Client Form  ??

**Comment by nancyespinoza** [comment]
Hi Tran! Sorry for the confusion.
This data element is not needed in the relationship form. It is located in the testing stage and the logic is also needed in the testing stage.

**Comment by chauthutran** [comment]
Hi Nancy,

Just want to make sure that this data element is showed when "Final HIV status" is  'Negative' , not "Positive".
