### ISSUE TITLE
Add LS HTS TRK - Comments/TCB - To Come Back (months/12) output in HTML Report

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#16]
Add the BZxUgzX4BpO Output in the report as follows:
![image](https://user-images.githubusercontent.com/44774809/92290037-f12b2900-eecf-11ea-9edf-bc0f2db2e3e9.png)

**Comment by chauthutran** [comment]
Hi Nancy,

Just want to let you know, before we used DE "E1KAxdya3y5" in column "Comments/TCB". So now, we are using DE "BZxUgzX4BpO" in this column.

**Comment by chauthutran** [comment]
Please test report "LS-HTS - MoH Register v13".
