### ISSUE TITLE
Capture “HIV status reported by index lead” and the “partner notification method” in LS HTS TRK - ContactLog – Comment(HaauwE6JkEs)

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#4]
1. Do not create a "previous test" tab
2. Add the values of bCVRuaX7LwG and Eis9qerhBFg in LS HTS TRK - ContactLog – Comment (HaauwE6JkEs) 

Example:
1. ![image](https://user-images.githubusercontent.com/44774809/90936464-6f60d900-e3c2-11ea-90ab-5d7483058a0f.png)
2. ![image](https://user-images.githubusercontent.com/44774809/90936528-99b29680-e3c2-11ea-89d0-d3f197abde3a.png)

**Comment by nancyespinoza** [comment]
**The information is not saved in LS HTS TRK - ContactLog – Comment (HaauwE6JkEs)**

These are the steps I followed:

1. Index new client
![20200827145350](https://user-images.githubusercontent.com/44774809/91493886-323e9000-e875-11ea-9540-a51c9aff3a50.gif)

2. Check contact log information (Contact log is not created)
![20200827145754](https://user-images.githubusercontent.com/44774809/91494199-b729a980-e875-11ea-9955-065bd962ebf8.gif)

**Comment by chauthutran** [comment]
It is fixed.

**Comment by nancyespinoza** [comment]
At first, it looks like the previous test tab is still being created but once you search the same client, the tab is gone.
![20200828083749](https://user-images.githubusercontent.com/44774809/91580060-c5290a00-e909-11ea-8cd1-8db4db22f783.gif)

**Comment by chauthutran** [comment]
Hi Nancy, I cannot simulate the bug in my side. I even used the same TEI ( Charles ... ) 
Can you give me one TEI which got the same issue OR give me more details how to create TEI with this issue ?

**Comment by nancyespinoza** [comment]
Hi Tran! I think the best way to replicate is:
1. Go to the indexing tab in any existing client
2. Add a new relationship
3. Create client
4. Go to the indexed client (the new client) - You'll see they have the prevous testing tab there
5. Make a search (using the search/create client button) - Search the client you just created in the indexing and you'll see the tab is no longer there.
