### ISSUE TITLE
"relationshipType"

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#7]
To create a relationship between 2 clients, we need to special who they are in relationship. For example, for "parent-child", relationship, we need to know who is parent, who is child.
In in "Add New Relationship" dialog form, with data element "relationshipType", we can special only the relationshipType, but we cannot special who is "parent/child" or "Lead/Contact".

 I suggest that in this case, we should add more one field to special the relationship "parent/child" or "Lead/Contact". This field can put below data element "relationshipType". How do you think

**Comment by chauthutran** [comment]
Hi Nancy, can you confirm about the idea here ? If it is not good, please let me know your idea to solve this issue.
Thank you.

**Comment by rodmelia** [comment]
Yes for both:
For Parent-Child - we need to understand who is the Parent, who is the child.
For Sexual Partner: Lead or contact.
Low priority

**Comment by nancyespinoza** [comment]
Sexual partner label is working fine but the parent-child is writing child in both clients
![20200827143853](https://user-images.githubusercontent.com/44774809/91492530-0d491d80-e873-11ea-8e4f-b4e85d0c3e26.gif)

**Comment by chauthutran** [comment]
This bug is fixed. Please test again in your side. Thank you
